{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "rook.io cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_health_status)" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_mon_quorum_count" }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_pool_bytes_used)" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes/ceph_cluster_total_bytes"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_osd_in)" }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(ceph_osd_numpg)" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes - ceph_cluster_total_used_bytes",
     "legendFormat": "Available"
    },
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Used" },
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_cluster_total_objects", "legendFormat": "Total" }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ceph_osd_numpg)", "legendFormat": "Total" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_stale", "legendFormat": "Stale" },
    { "expr": "ceph_pg_inconsistent", "legendFormat": "Inconsistent" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    {
     "expr": "ceph_stuck_degraded_pgs + ceph_stuck_stale_pgs + ceph_stuck_unclean_pgs + ceph_stuck_undersized_pgs",
     "legendFormat": "Stuck"
    }
   ]
  }
 ]
}