apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: rook
data:
  prometheus.yaml: |+
    datasources:
     - name: prometheus
       type: prometheus
       access: proxy
       org_id: 1
       url: http://rook-prometheus:9090
       version: 1
       editable: false

